### ISSUE TITLE
iOS WeChat 分享地址问题

### ISSUE THREAD

**Issue by 438198602** [code-mcx/mango-music#3]
我的项目使用了react-router v4，我用微信打开一个页面，然后进入另一个页面，这时用微信自带的分享好友、朋友圈或者复制链接得到的地址是上一个页面的地址，我试了你的项目也是这样，Android的微信没这个问题。网上说是iOS微信的原因，请问有什么方法解决这个问题吗？

**Comment by mocaitian** [comment]
一个不完美的办法是每次进到一个新页面就reload一下
