### ISSUE TITLE
跨域请求的问题

### ISSUE THREAD

**Issue by ghost** [code-mcx/mango-music#4]
想请问下,如何处理跨域请求?

`vue-cli`脚手架搭建项目撸代码的时候,可以在`webpack` 中配置 `proxyTable`来进行代理,实现跨域请求诸如豆瓣、猫眼等这些接口数据;
但是用`react`脚手架`create-react-app`撸的时候,执行 `npm run eject`解出`webpack`配置,中并没有这个配置选项,所以我想请问下怎么实现?

**Comment by dxx** [comment]
执行`npm run eject`后，在scripts/start.js中有一行`const proxySetting = require(paths.appPackageJson).proxy`，这个paths是在config/paths.js中`module.exports`出的对象中的属性，appPackageJson则是package.json解析出的对象，proxy就是对应的代理配置对象。在package.json中配置proxy节点，节点配置和proxyTable类同
