### ISSUE TITLE
why not make good use of redux

### ISSUE THREAD

**Issue by lyneverless** [code-mcx/mango-music#6]
there are only 4 reducers which are very simple and not pure(calling localstorage)

**Comment by dxx** [comment]
Too many place need to call `localStorage`, just for convenient. Before this i don't know how to write a middleware, i think the best way to call `localSorage` is use middleware. Now i have resolved it by use middleware. Look at [here](https://github.com/code-mcx/mango-music/commit/8d0091e4e15a1eb5d65e4e1ca5a692ee88d2e8fc).
